fix(prefect-server): remove deprecated helpers (#487)
Follow-up to https://github.com/PrefectHQ/prefect-helm/pull/486,
which included https://github.com/bitnami/charts/pull/33496 that removed
unused helpers. We need to remove them here as well.

Reported in community:

> Error: template: prefect-server/templates/ingress.yaml:23:51:
> executing "prefect-server/templates/ingress.yaml" at
> <include "common.ingress.supportsIngressClassname" .>: error calling include:
> template: no template "common.ingress.supportsIngressClassname" associated with template "gotpl"

Related to https://linear.app/prefect/issue/PLA-1479/cycle-19-catch-all